spring:
  datasource:
    dynamic:
      p6spy: true

      druid: #以下是全局默认值，可以全局更改
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: druid
          login-password: 123456
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: false
          wall:
            config:
              multi-statement-allow: true

      datasource:
        master:
          url: jdbc:mysql://rm-2ze89v2lo60myyqf9fo.mysql.rds.aliyuncs.com:3306/oa?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
          username: chetubao
          password: Beijing2017
          driver-class-name: com.mysql.jdbc.Driver
          druid: #这里可以重写默认值
            initial-size: 5
        hudong:
          url: jdbc:mysql://rm-2zeq7f09ka2n496k2o.mysql.rds.aliyuncs.com:3306/hudong_test?characterEncoding=utf8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true
          username: yuanweiwangluo
          password: Beijing2017
          driver-class-name: com.mysql.jdbc.Driver
          druid:
            initial-size: 6
#        slave_2:
#          username: sa
#          password: "123456"
#          url: jdbc:h2:mem:test
#          driver-class-name: org.h2.Driver

logging:
  level:
    com.baomidou: debug